name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: mvn test

  bump-version-and-tag:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        release_branches: main
        create_annotated_tag: true

  create-changelog:
    needs: bump-version-and-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump-version-and-tag.outputs.new_tag }}
        release_name: Release ${{ steps.bump-version-and-tag.outputs.new_tag }}
        body_path: changelog.md
    - name: Generate changelog
      uses: mikepenz/release-changelog-builder-action@v2.4.4
      with:
        configuration: .github/changelog_configuration.yml
        token: ${{ secrets.GITHUB_TOKEN }}
